name: Test Aggregate Comments Action

on:
  push:
    branches:
      - main

  workflow_dispatch: # Manually trigger the workflow

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: zhongkairen/compile-issue-comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-name: "epic"
          comment-prefix: "[week02]"
          discussion-heading: "Week 02"
