name: Test Aggregate Comments Action

on:
  push:
    branches:
      - main

  workflow_dispatch: # Manually trigger the workflow

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Test Action
        uses: ./ # Use the action in the current repo for testing
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-name: "bug"
          comment-prefix: "DISCUSSION:"
          discussion-title: "Test Aggregated Comments"
